/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoanIndexRouteImport } from './routes/loan/index'
import { Route as LoanSetupRouteImport } from './routes/loan/setup'
import { Route as LoanScorecardsRouteImport } from './routes/loan/scorecards'
import { Route as LoanScorecardSetupRouteImport } from './routes/loan/scorecard-setup'
import { Route as LoanRepaymentSetupRouteImport } from './routes/loan/repayment-setup'
import { Route as LoanApplicationsIndexRouteImport } from './routes/loan/applications/index'
import { Route as LoanApplicationsCreateRouteImport } from './routes/loan/applications/create'
import { Route as LoanApplicationsApplicationIdRouteImport } from './routes/loan/applications/$applicationId'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanIndexRoute = LoanIndexRouteImport.update({
  id: '/loan/',
  path: '/loan/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanSetupRoute = LoanSetupRouteImport.update({
  id: '/loan/setup',
  path: '/loan/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanScorecardsRoute = LoanScorecardsRouteImport.update({
  id: '/loan/scorecards',
  path: '/loan/scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanScorecardSetupRoute = LoanScorecardSetupRouteImport.update({
  id: '/loan/scorecard-setup',
  path: '/loan/scorecard-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRepaymentSetupRoute = LoanRepaymentSetupRouteImport.update({
  id: '/loan/repayment-setup',
  path: '/loan/repayment-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationsIndexRoute = LoanApplicationsIndexRouteImport.update({
  id: '/loan/applications/',
  path: '/loan/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationsCreateRoute = LoanApplicationsCreateRouteImport.update({
  id: '/loan/applications/create',
  path: '/loan/applications/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationsApplicationIdRoute =
  LoanApplicationsApplicationIdRouteImport.update({
    id: '/loan/applications/$applicationId',
    path: '/loan/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflow': typeof WorkflowRoute
  '/loan/repayment-setup': typeof LoanRepaymentSetupRoute
  '/loan/scorecard-setup': typeof LoanScorecardSetupRoute
  '/loan/scorecards': typeof LoanScorecardsRoute
  '/loan/setup': typeof LoanSetupRoute
  '/loan': typeof LoanIndexRoute
  '/loan/applications/$applicationId': typeof LoanApplicationsApplicationIdRoute
  '/loan/applications/create': typeof LoanApplicationsCreateRoute
  '/loan/applications': typeof LoanApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflow': typeof WorkflowRoute
  '/loan/repayment-setup': typeof LoanRepaymentSetupRoute
  '/loan/scorecard-setup': typeof LoanScorecardSetupRoute
  '/loan/scorecards': typeof LoanScorecardsRoute
  '/loan/setup': typeof LoanSetupRoute
  '/loan': typeof LoanIndexRoute
  '/loan/applications/$applicationId': typeof LoanApplicationsApplicationIdRoute
  '/loan/applications/create': typeof LoanApplicationsCreateRoute
  '/loan/applications': typeof LoanApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workflow': typeof WorkflowRoute
  '/loan/repayment-setup': typeof LoanRepaymentSetupRoute
  '/loan/scorecard-setup': typeof LoanScorecardSetupRoute
  '/loan/scorecards': typeof LoanScorecardsRoute
  '/loan/setup': typeof LoanSetupRoute
  '/loan/': typeof LoanIndexRoute
  '/loan/applications/$applicationId': typeof LoanApplicationsApplicationIdRoute
  '/loan/applications/create': typeof LoanApplicationsCreateRoute
  '/loan/applications/': typeof LoanApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflow'
    | '/loan/repayment-setup'
    | '/loan/scorecard-setup'
    | '/loan/scorecards'
    | '/loan/setup'
    | '/loan'
    | '/loan/applications/$applicationId'
    | '/loan/applications/create'
    | '/loan/applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workflow'
    | '/loan/repayment-setup'
    | '/loan/scorecard-setup'
    | '/loan/scorecards'
    | '/loan/setup'
    | '/loan'
    | '/loan/applications/$applicationId'
    | '/loan/applications/create'
    | '/loan/applications'
  id:
    | '__root__'
    | '/'
    | '/workflow'
    | '/loan/repayment-setup'
    | '/loan/scorecard-setup'
    | '/loan/scorecards'
    | '/loan/setup'
    | '/loan/'
    | '/loan/applications/$applicationId'
    | '/loan/applications/create'
    | '/loan/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkflowRoute: typeof WorkflowRoute
  LoanRepaymentSetupRoute: typeof LoanRepaymentSetupRoute
  LoanScorecardSetupRoute: typeof LoanScorecardSetupRoute
  LoanScorecardsRoute: typeof LoanScorecardsRoute
  LoanSetupRoute: typeof LoanSetupRoute
  LoanIndexRoute: typeof LoanIndexRoute
  LoanApplicationsApplicationIdRoute: typeof LoanApplicationsApplicationIdRoute
  LoanApplicationsCreateRoute: typeof LoanApplicationsCreateRoute
  LoanApplicationsIndexRoute: typeof LoanApplicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/': {
      id: '/loan/'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/setup': {
      id: '/loan/setup'
      path: '/loan/setup'
      fullPath: '/loan/setup'
      preLoaderRoute: typeof LoanSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/scorecards': {
      id: '/loan/scorecards'
      path: '/loan/scorecards'
      fullPath: '/loan/scorecards'
      preLoaderRoute: typeof LoanScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/scorecard-setup': {
      id: '/loan/scorecard-setup'
      path: '/loan/scorecard-setup'
      fullPath: '/loan/scorecard-setup'
      preLoaderRoute: typeof LoanScorecardSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/repayment-setup': {
      id: '/loan/repayment-setup'
      path: '/loan/repayment-setup'
      fullPath: '/loan/repayment-setup'
      preLoaderRoute: typeof LoanRepaymentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/applications/': {
      id: '/loan/applications/'
      path: '/loan/applications'
      fullPath: '/loan/applications'
      preLoaderRoute: typeof LoanApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/applications/create': {
      id: '/loan/applications/create'
      path: '/loan/applications/create'
      fullPath: '/loan/applications/create'
      preLoaderRoute: typeof LoanApplicationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/applications/$applicationId': {
      id: '/loan/applications/$applicationId'
      path: '/loan/applications/$applicationId'
      fullPath: '/loan/applications/$applicationId'
      preLoaderRoute: typeof LoanApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowRoute: WorkflowRoute,
  LoanRepaymentSetupRoute: LoanRepaymentSetupRoute,
  LoanScorecardSetupRoute: LoanScorecardSetupRoute,
  LoanScorecardsRoute: LoanScorecardsRoute,
  LoanSetupRoute: LoanSetupRoute,
  LoanIndexRoute: LoanIndexRoute,
  LoanApplicationsApplicationIdRoute: LoanApplicationsApplicationIdRoute,
  LoanApplicationsCreateRoute: LoanApplicationsCreateRoute,
  LoanApplicationsIndexRoute: LoanApplicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
