/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowIndexRouteImport } from './routes/workflow/index'
import { Route as LoanIndexRouteImport } from './routes/loan/index'
import { Route as WorkflowSetupRouteImport } from './routes/workflow/setup'
import { Route as WorkflowWorkflowIdRouteImport } from './routes/workflow/$workflowId'
import { Route as LoanScorecardsRouteImport } from './routes/loan/scorecards'
import { Route as LoanScorecardSetupAdvancedRouteImport } from './routes/loan/scorecard-setup-advanced'
import { Route as LoanScorecardSetupRouteImport } from './routes/loan/scorecard-setup'
import { Route as LoanRepaymentSetupRouteImport } from './routes/loan/repayment-setup'
import { Route as LoanRepaymentPlansRouteImport } from './routes/loan/repayment-plans'
import { Route as LoanEmiCustomCalculatorRouteImport } from './routes/loan/emi-custom-calculator'
import { Route as LoanEmiCalculatorRouteImport } from './routes/loan/emi-calculator'
import { Route as LoanSetupIndexRouteImport } from './routes/loan/setup/index'
import { Route as LoanMakerInboxIndexRouteImport } from './routes/loan/maker-inbox/index'
import { Route as LoanCheckerInboxIndexRouteImport } from './routes/loan/checker-inbox/index'
import { Route as LoanApplicationsIndexRouteImport } from './routes/loan/applications/index'
import { Route as SolutionV2LoanSetupRouteImport } from './routes/solution/v2/loan-setup'
import { Route as LoanSetupSetupIdRouteImport } from './routes/loan/setup/$setupId'
import { Route as LoanMakerInboxApplicationIdRouteImport } from './routes/loan/maker-inbox/$applicationId'
import { Route as LoanCheckerInboxApplicationIdRouteImport } from './routes/loan/checker-inbox/$applicationId'
import { Route as LoanApplicationsCreateRouteImport } from './routes/loan/applications/create'
import { Route as LoanApplicationsApplicationIdRouteImport } from './routes/loan/applications/$applicationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanIndexRoute = LoanIndexRouteImport.update({
  id: '/loan/',
  path: '/loan/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowSetupRoute = WorkflowSetupRouteImport.update({
  id: '/workflow/setup',
  path: '/workflow/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowIdRoute = WorkflowWorkflowIdRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanScorecardsRoute = LoanScorecardsRouteImport.update({
  id: '/loan/scorecards',
  path: '/loan/scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanScorecardSetupAdvancedRoute =
  LoanScorecardSetupAdvancedRouteImport.update({
    id: '/loan/scorecard-setup-advanced',
    path: '/loan/scorecard-setup-advanced',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoanScorecardSetupRoute = LoanScorecardSetupRouteImport.update({
  id: '/loan/scorecard-setup',
  path: '/loan/scorecard-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRepaymentSetupRoute = LoanRepaymentSetupRouteImport.update({
  id: '/loan/repayment-setup',
  path: '/loan/repayment-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRepaymentPlansRoute = LoanRepaymentPlansRouteImport.update({
  id: '/loan/repayment-plans',
  path: '/loan/repayment-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanEmiCustomCalculatorRoute = LoanEmiCustomCalculatorRouteImport.update({
  id: '/loan/emi-custom-calculator',
  path: '/loan/emi-custom-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanEmiCalculatorRoute = LoanEmiCalculatorRouteImport.update({
  id: '/loan/emi-calculator',
  path: '/loan/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanSetupIndexRoute = LoanSetupIndexRouteImport.update({
  id: '/loan/setup/',
  path: '/loan/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanMakerInboxIndexRoute = LoanMakerInboxIndexRouteImport.update({
  id: '/loan/maker-inbox/',
  path: '/loan/maker-inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCheckerInboxIndexRoute = LoanCheckerInboxIndexRouteImport.update({
  id: '/loan/checker-inbox/',
  path: '/loan/checker-inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationsIndexRoute = LoanApplicationsIndexRouteImport.update({
  id: '/loan/applications/',
  path: '/loan/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionV2LoanSetupRoute = SolutionV2LoanSetupRouteImport.update({
  id: '/solution/v2/loan-setup',
  path: '/solution/v2/loan-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanSetupSetupIdRoute = LoanSetupSetupIdRouteImport.update({
  id: '/loan/setup/$setupId',
  path: '/loan/setup/$setupId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanMakerInboxApplicationIdRoute =
  LoanMakerInboxApplicationIdRouteImport.update({
    id: '/loan/maker-inbox/$applicationId',
    path: '/loan/maker-inbox/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoanCheckerInboxApplicationIdRoute =
  LoanCheckerInboxApplicationIdRouteImport.update({
    id: '/loan/checker-inbox/$applicationId',
    path: '/loan/checker-inbox/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoanApplicationsCreateRoute = LoanApplicationsCreateRouteImport.update({
  id: '/loan/applications/create',
  path: '/loan/applications/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationsApplicationIdRoute =
  LoanApplicationsApplicationIdRouteImport.update({
    id: '/loan/applications/$applicationId',
    path: '/loan/applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/loan/emi-calculator': typeof LoanEmiCalculatorRoute
  '/loan/emi-custom-calculator': typeof LoanEmiCustomCalculatorRoute
  '/loan/repayment-plans': typeof LoanRepaymentPlansRoute
  '/loan/repayment-setup': typeof LoanRepaymentSetupRoute
  '/loan/scorecard-setup': typeof LoanScorecardSetupRoute
  '/loan/scorecard-setup-advanced': typeof LoanScorecardSetupAdvancedRoute
  '/loan/scorecards': typeof LoanScorecardsRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/workflow/setup': typeof WorkflowSetupRoute
  '/loan': typeof LoanIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/loan/applications/$applicationId': typeof LoanApplicationsApplicationIdRoute
  '/loan/applications/create': typeof LoanApplicationsCreateRoute
  '/loan/checker-inbox/$applicationId': typeof LoanCheckerInboxApplicationIdRoute
  '/loan/maker-inbox/$applicationId': typeof LoanMakerInboxApplicationIdRoute
  '/loan/setup/$setupId': typeof LoanSetupSetupIdRoute
  '/solution/v2/loan-setup': typeof SolutionV2LoanSetupRoute
  '/loan/applications': typeof LoanApplicationsIndexRoute
  '/loan/checker-inbox': typeof LoanCheckerInboxIndexRoute
  '/loan/maker-inbox': typeof LoanMakerInboxIndexRoute
  '/loan/setup': typeof LoanSetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/loan/emi-calculator': typeof LoanEmiCalculatorRoute
  '/loan/emi-custom-calculator': typeof LoanEmiCustomCalculatorRoute
  '/loan/repayment-plans': typeof LoanRepaymentPlansRoute
  '/loan/repayment-setup': typeof LoanRepaymentSetupRoute
  '/loan/scorecard-setup': typeof LoanScorecardSetupRoute
  '/loan/scorecard-setup-advanced': typeof LoanScorecardSetupAdvancedRoute
  '/loan/scorecards': typeof LoanScorecardsRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/workflow/setup': typeof WorkflowSetupRoute
  '/loan': typeof LoanIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/loan/applications/$applicationId': typeof LoanApplicationsApplicationIdRoute
  '/loan/applications/create': typeof LoanApplicationsCreateRoute
  '/loan/checker-inbox/$applicationId': typeof LoanCheckerInboxApplicationIdRoute
  '/loan/maker-inbox/$applicationId': typeof LoanMakerInboxApplicationIdRoute
  '/loan/setup/$setupId': typeof LoanSetupSetupIdRoute
  '/solution/v2/loan-setup': typeof SolutionV2LoanSetupRoute
  '/loan/applications': typeof LoanApplicationsIndexRoute
  '/loan/checker-inbox': typeof LoanCheckerInboxIndexRoute
  '/loan/maker-inbox': typeof LoanMakerInboxIndexRoute
  '/loan/setup': typeof LoanSetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/loan/emi-calculator': typeof LoanEmiCalculatorRoute
  '/loan/emi-custom-calculator': typeof LoanEmiCustomCalculatorRoute
  '/loan/repayment-plans': typeof LoanRepaymentPlansRoute
  '/loan/repayment-setup': typeof LoanRepaymentSetupRoute
  '/loan/scorecard-setup': typeof LoanScorecardSetupRoute
  '/loan/scorecard-setup-advanced': typeof LoanScorecardSetupAdvancedRoute
  '/loan/scorecards': typeof LoanScorecardsRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/workflow/setup': typeof WorkflowSetupRoute
  '/loan/': typeof LoanIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/loan/applications/$applicationId': typeof LoanApplicationsApplicationIdRoute
  '/loan/applications/create': typeof LoanApplicationsCreateRoute
  '/loan/checker-inbox/$applicationId': typeof LoanCheckerInboxApplicationIdRoute
  '/loan/maker-inbox/$applicationId': typeof LoanMakerInboxApplicationIdRoute
  '/loan/setup/$setupId': typeof LoanSetupSetupIdRoute
  '/solution/v2/loan-setup': typeof SolutionV2LoanSetupRoute
  '/loan/applications/': typeof LoanApplicationsIndexRoute
  '/loan/checker-inbox/': typeof LoanCheckerInboxIndexRoute
  '/loan/maker-inbox/': typeof LoanMakerInboxIndexRoute
  '/loan/setup/': typeof LoanSetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/loan/emi-calculator'
    | '/loan/emi-custom-calculator'
    | '/loan/repayment-plans'
    | '/loan/repayment-setup'
    | '/loan/scorecard-setup'
    | '/loan/scorecard-setup-advanced'
    | '/loan/scorecards'
    | '/workflow/$workflowId'
    | '/workflow/setup'
    | '/loan'
    | '/workflow'
    | '/loan/applications/$applicationId'
    | '/loan/applications/create'
    | '/loan/checker-inbox/$applicationId'
    | '/loan/maker-inbox/$applicationId'
    | '/loan/setup/$setupId'
    | '/solution/v2/loan-setup'
    | '/loan/applications'
    | '/loan/checker-inbox'
    | '/loan/maker-inbox'
    | '/loan/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/loan/emi-calculator'
    | '/loan/emi-custom-calculator'
    | '/loan/repayment-plans'
    | '/loan/repayment-setup'
    | '/loan/scorecard-setup'
    | '/loan/scorecard-setup-advanced'
    | '/loan/scorecards'
    | '/workflow/$workflowId'
    | '/workflow/setup'
    | '/loan'
    | '/workflow'
    | '/loan/applications/$applicationId'
    | '/loan/applications/create'
    | '/loan/checker-inbox/$applicationId'
    | '/loan/maker-inbox/$applicationId'
    | '/loan/setup/$setupId'
    | '/solution/v2/loan-setup'
    | '/loan/applications'
    | '/loan/checker-inbox'
    | '/loan/maker-inbox'
    | '/loan/setup'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/loan/emi-calculator'
    | '/loan/emi-custom-calculator'
    | '/loan/repayment-plans'
    | '/loan/repayment-setup'
    | '/loan/scorecard-setup'
    | '/loan/scorecard-setup-advanced'
    | '/loan/scorecards'
    | '/workflow/$workflowId'
    | '/workflow/setup'
    | '/loan/'
    | '/workflow/'
    | '/loan/applications/$applicationId'
    | '/loan/applications/create'
    | '/loan/checker-inbox/$applicationId'
    | '/loan/maker-inbox/$applicationId'
    | '/loan/setup/$setupId'
    | '/solution/v2/loan-setup'
    | '/loan/applications/'
    | '/loan/checker-inbox/'
    | '/loan/maker-inbox/'
    | '/loan/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LoanEmiCalculatorRoute: typeof LoanEmiCalculatorRoute
  LoanEmiCustomCalculatorRoute: typeof LoanEmiCustomCalculatorRoute
  LoanRepaymentPlansRoute: typeof LoanRepaymentPlansRoute
  LoanRepaymentSetupRoute: typeof LoanRepaymentSetupRoute
  LoanScorecardSetupRoute: typeof LoanScorecardSetupRoute
  LoanScorecardSetupAdvancedRoute: typeof LoanScorecardSetupAdvancedRoute
  LoanScorecardsRoute: typeof LoanScorecardsRoute
  WorkflowWorkflowIdRoute: typeof WorkflowWorkflowIdRoute
  WorkflowSetupRoute: typeof WorkflowSetupRoute
  LoanIndexRoute: typeof LoanIndexRoute
  WorkflowIndexRoute: typeof WorkflowIndexRoute
  LoanApplicationsApplicationIdRoute: typeof LoanApplicationsApplicationIdRoute
  LoanApplicationsCreateRoute: typeof LoanApplicationsCreateRoute
  LoanCheckerInboxApplicationIdRoute: typeof LoanCheckerInboxApplicationIdRoute
  LoanMakerInboxApplicationIdRoute: typeof LoanMakerInboxApplicationIdRoute
  LoanSetupSetupIdRoute: typeof LoanSetupSetupIdRoute
  SolutionV2LoanSetupRoute: typeof SolutionV2LoanSetupRoute
  LoanApplicationsIndexRoute: typeof LoanApplicationsIndexRoute
  LoanCheckerInboxIndexRoute: typeof LoanCheckerInboxIndexRoute
  LoanMakerInboxIndexRoute: typeof LoanMakerInboxIndexRoute
  LoanSetupIndexRoute: typeof LoanSetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/': {
      id: '/loan/'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/setup': {
      id: '/workflow/setup'
      path: '/workflow/setup'
      fullPath: '/workflow/setup'
      preLoaderRoute: typeof WorkflowSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowId': {
      id: '/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof WorkflowWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/scorecards': {
      id: '/loan/scorecards'
      path: '/loan/scorecards'
      fullPath: '/loan/scorecards'
      preLoaderRoute: typeof LoanScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/scorecard-setup-advanced': {
      id: '/loan/scorecard-setup-advanced'
      path: '/loan/scorecard-setup-advanced'
      fullPath: '/loan/scorecard-setup-advanced'
      preLoaderRoute: typeof LoanScorecardSetupAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/scorecard-setup': {
      id: '/loan/scorecard-setup'
      path: '/loan/scorecard-setup'
      fullPath: '/loan/scorecard-setup'
      preLoaderRoute: typeof LoanScorecardSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/repayment-setup': {
      id: '/loan/repayment-setup'
      path: '/loan/repayment-setup'
      fullPath: '/loan/repayment-setup'
      preLoaderRoute: typeof LoanRepaymentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/repayment-plans': {
      id: '/loan/repayment-plans'
      path: '/loan/repayment-plans'
      fullPath: '/loan/repayment-plans'
      preLoaderRoute: typeof LoanRepaymentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/emi-custom-calculator': {
      id: '/loan/emi-custom-calculator'
      path: '/loan/emi-custom-calculator'
      fullPath: '/loan/emi-custom-calculator'
      preLoaderRoute: typeof LoanEmiCustomCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/emi-calculator': {
      id: '/loan/emi-calculator'
      path: '/loan/emi-calculator'
      fullPath: '/loan/emi-calculator'
      preLoaderRoute: typeof LoanEmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/setup/': {
      id: '/loan/setup/'
      path: '/loan/setup'
      fullPath: '/loan/setup'
      preLoaderRoute: typeof LoanSetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/maker-inbox/': {
      id: '/loan/maker-inbox/'
      path: '/loan/maker-inbox'
      fullPath: '/loan/maker-inbox'
      preLoaderRoute: typeof LoanMakerInboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/checker-inbox/': {
      id: '/loan/checker-inbox/'
      path: '/loan/checker-inbox'
      fullPath: '/loan/checker-inbox'
      preLoaderRoute: typeof LoanCheckerInboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/applications/': {
      id: '/loan/applications/'
      path: '/loan/applications'
      fullPath: '/loan/applications'
      preLoaderRoute: typeof LoanApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution/v2/loan-setup': {
      id: '/solution/v2/loan-setup'
      path: '/solution/v2/loan-setup'
      fullPath: '/solution/v2/loan-setup'
      preLoaderRoute: typeof SolutionV2LoanSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/setup/$setupId': {
      id: '/loan/setup/$setupId'
      path: '/loan/setup/$setupId'
      fullPath: '/loan/setup/$setupId'
      preLoaderRoute: typeof LoanSetupSetupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/maker-inbox/$applicationId': {
      id: '/loan/maker-inbox/$applicationId'
      path: '/loan/maker-inbox/$applicationId'
      fullPath: '/loan/maker-inbox/$applicationId'
      preLoaderRoute: typeof LoanMakerInboxApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/checker-inbox/$applicationId': {
      id: '/loan/checker-inbox/$applicationId'
      path: '/loan/checker-inbox/$applicationId'
      fullPath: '/loan/checker-inbox/$applicationId'
      preLoaderRoute: typeof LoanCheckerInboxApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/applications/create': {
      id: '/loan/applications/create'
      path: '/loan/applications/create'
      fullPath: '/loan/applications/create'
      preLoaderRoute: typeof LoanApplicationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/applications/$applicationId': {
      id: '/loan/applications/$applicationId'
      path: '/loan/applications/$applicationId'
      fullPath: '/loan/applications/$applicationId'
      preLoaderRoute: typeof LoanApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LoanEmiCalculatorRoute: LoanEmiCalculatorRoute,
  LoanEmiCustomCalculatorRoute: LoanEmiCustomCalculatorRoute,
  LoanRepaymentPlansRoute: LoanRepaymentPlansRoute,
  LoanRepaymentSetupRoute: LoanRepaymentSetupRoute,
  LoanScorecardSetupRoute: LoanScorecardSetupRoute,
  LoanScorecardSetupAdvancedRoute: LoanScorecardSetupAdvancedRoute,
  LoanScorecardsRoute: LoanScorecardsRoute,
  WorkflowWorkflowIdRoute: WorkflowWorkflowIdRoute,
  WorkflowSetupRoute: WorkflowSetupRoute,
  LoanIndexRoute: LoanIndexRoute,
  WorkflowIndexRoute: WorkflowIndexRoute,
  LoanApplicationsApplicationIdRoute: LoanApplicationsApplicationIdRoute,
  LoanApplicationsCreateRoute: LoanApplicationsCreateRoute,
  LoanCheckerInboxApplicationIdRoute: LoanCheckerInboxApplicationIdRoute,
  LoanMakerInboxApplicationIdRoute: LoanMakerInboxApplicationIdRoute,
  LoanSetupSetupIdRoute: LoanSetupSetupIdRoute,
  SolutionV2LoanSetupRoute: SolutionV2LoanSetupRoute,
  LoanApplicationsIndexRoute: LoanApplicationsIndexRoute,
  LoanCheckerInboxIndexRoute: LoanCheckerInboxIndexRoute,
  LoanMakerInboxIndexRoute: LoanMakerInboxIndexRoute,
  LoanSetupIndexRoute: LoanSetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
